### ISSUE TITLE
[FEATURE] Support for distributed learning 

### ISSUE THREAD

**Issue by robbrad** [MouseLand/cellpose#733] opened 2023-06-21 10:15 UTC
**Is your feature request related to a problem? Please describe.**
Could Cellpose use something like [SageMaker SDK
](https://docs.aws.amazon.com/sagemaker/latest/dg/distributed-training.html)

To perform distributed training - allowing for the GUI / Human in the loop to be separated from the instance doing the training?

**Describe the solution you'd like**
When the user clicks the model it would make a call to the Sagemaker to perform the training remotely

**Additional context**
Prob only really useful if the training time is going to take a long time.

**Comment by mrariden** [comment] 2023-06-21 20:46
Sounds like a duplicate of #725. I think that implementing something like SageMaker is beyond the scope of the Cellpose project @carsen-stringer ?

**Comment by carsen-stringer** [comment] 2024-09-12 08:00
yeah this is not something we plan to support, you can fork the repo and add this sort of functionality

**Closed by carsen-stringer** 2024-09-12 08:00 UTC
Labels: enhancement
