### ISSUE TITLE
_seg.npy output

### ISSUE THREAD

**Issue by motviybletb** [MouseLand/cellpose#800] opened 2023-10-05 14:58 UTC
Here is a structure of *_seg.npy file in cellpose documentation:

filename, img, masks, outlines, chan_choose, ismanual, flows, est_diam, zdraw

And here is a structure I see while trying to open npy file in python:

'outlines', 'colors', 'masks', 'chan_choose', 'filename', 'flows', 'ismanual', 'manual_changes', 'model_path', 'flow_threshold', 'cellprob_threshold'

Why are they so different and how can I open my file in python?

**Comment by mrariden** [comment] 2023-10-05 16:34
Hi, we can update the documentation. The .npy file is used to collect all the information for a image, and similar information is available from the CLI if the correct flags are used (`--save_png` for example). 

The data is stored in dictionary object. Use `data = np.load(file, allow_pickle=True).item()` to load the dictionary.

**Comment by mrariden** [comment] 2023-10-06 13:30
Yes, the outlines of the masks are the value of the 'outlines' key.

**Comment by mrariden** [comment] 2023-11-03 13:38
closing, reopen if needed

**Closed by mrariden** 2023-11-03 13:38 UTC
Labels: documentation

**Comment by Nero-Rome** [comment] 2024-02-11 21:08
Hi!

**Comment by Nero-Rome** [comment] 2024-02-11 21:10
Hi! Same problem here. I can load the .npy file into python, but by checking the keys of the dictionary, I get the same as @motviybletb 

The problem is that with "img" missing as a key, I cannot plot out the graphs following the instructions here: https://cellpose.readthedocs.io/en/latest/outputs.html 

Any help will be appreciated!

**Comment by nidhihosamane** [comment] 2024-02-14 16:09
Hi! I also am having the same issue- the documentation does not seem to match, and I also do not have the "img" key in the dictionary. How else can I access these values?

**Comment by mrariden** [comment] 2024-02-16 19:05
The `img` key was removed to speed up saving the .npy file when editing masks. They value of the key is just the original image saved in a numpy array, so the data is identical to your original image file data.
