### ISSUE TITLE
[BUG] can't draw segmentation boundries

### ISSUE THREAD

**Issue by pvtodorov** [MouseLand/cellpose#702] opened 2023-05-06 11:16 UTC
**Description**
Right clicking in cellpose GUI to draw boundaries does not produce boundaries but purple dots. These never form boundaries like in the video. It's impossible to make the purple dots stop being added, as new right clicks aren't registered. To stop this, the session must be closed. May be related to #701 

**Video**
https://www.youtube.com/watch?v=k0R5D6oF2Yw
[![Alt text](https://img.youtube.com/vi/k0R5D6oF2Yw/0.jpg)](https://www.youtube.com/watch?v=k0R5D6oF2Yw)
**Run log**
```
(cellpose) C:\Users\petar>python -m cellpose
2023-05-06 13:03:37,683 [INFO] WRITING LOG OUTPUT TO C:\Users\petar\.cellpose\run.log
2023-05-06 13:03:37,683 [INFO]
cellpose version:       2.3.dev24+g3ca6a8f
platform:               win32
python version:         3.10.10
torch version:          2.0.0
2023-05-06 13:03:38,228 [INFO] ** TORCH CUDA version installed and working. **
GUI_INFO: loading image: C:/Users/petar/Desktop/A1/New folder/03r/Composite-03r.tif
(8748, 8112, 4)
GUI_INFO: auto-adjust enabled, computing saturation levels
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
QGraphicsScene::removeItem: item 0x1d96341f300's scene (0x0) is different from this scene (0x1d9682e6170)
```

Installed in conda environment
```
(cellpose) C:\Users\petar>conda list
# packages in environment at C:\Users\petar\mambaforge\envs\cellpose:
#
# Name                    Version                   Build  Channel
blas                      2.116                       mkl    conda-forge
blas-devel                3.9.0              16_win64_mkl    conda-forge
brotlipy                  0.7.0           py310h8d17308_1005    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2022.12.7            h5b45459_0    conda-forge
cellpose                  2.3.dev24+g3ca6a8f          pypi_0    pypi
certifi                   2022.12.7          pyhd8ed1ab_0    conda-forge
cffi                      1.15.1          py310h628cb3f_3    conda-forge
charset-normalizer        3.1.0              pyhd8ed1ab_0    conda-forge
colorama                  0.4.6                    pypi_0    pypi
cryptography              40.0.2          py310h6e82f81_0    conda-forge
cuda-cccl                 12.1.109                      0    nvidia
cuda-cudart               11.7.99                       0    nvidia
cuda-cudart-dev           11.7.99                       0    nvidia
cuda-cupti                11.7.101                      0    nvidia
cuda-libraries            11.7.1                        0    nvidia
cuda-libraries-dev        11.7.1                        0    nvidia
cuda-nvrtc                11.7.99                       0    nvidia
cuda-nvrtc-dev            11.7.99                       0    nvidia
cuda-nvtx                 11.7.91                       0    nvidia
cuda-runtime              11.7.1                        0    nvidia
fastremap                 1.13.4                   pypi_0    pypi
filelock                  3.12.0             pyhd8ed1ab_0    conda-forge
freetype                  2.12.1               h546665d_1    conda-forge
idna                      3.4                pyhd8ed1ab_0    conda-forge
imagecodecs               2023.3.16                pypi_0    pypi
intel-openmp              2023.1.0         h57928b3_46319    conda-forge
jinja2                    3.1.2              pyhd8ed1ab_1    conda-forge
jpeg                      9e                   hcfcfb64_3    conda-forge
lcms2                     2.15                 ha5c8aab_0    conda-forge
lerc                      4.0.0                h63175ca_0    conda-forge
libblas                   3.9.0              16_win64_mkl    conda-forge
libcblas                  3.9.0              16_win64_mkl    conda-forge
libcublas                 11.10.3.66                    0    nvidia
libcublas-dev             11.10.3.66                    0    nvidia
libcufft                  10.7.2.124                    0    nvidia
libcufft-dev              10.7.2.124                    0    nvidia
libcurand                 10.3.2.106                    0    nvidia
libcurand-dev             10.3.2.106                    0    nvidia
libcusolver               11.4.0.1                      0    nvidia
libcusolver-dev           11.4.0.1                      0    nvidia
libcusparse               11.7.4.91                     0    nvidia
libcusparse-dev           11.7.4.91                     0    nvidia
libdeflate                1.17                 hcfcfb64_0    conda-forge
libffi                    3.4.2                h8ffe710_5    conda-forge
libhwloc                  2.9.1                h51c2c0f_0    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
liblapack                 3.9.0              16_win64_mkl    conda-forge
liblapacke                3.9.0              16_win64_mkl    conda-forge
libnpp                    11.7.4.75                     0    nvidia
libnpp-dev                11.7.4.75                     0    nvidia
libnvjpeg                 11.8.0.2                      0    nvidia
libnvjpeg-dev             11.8.0.2                      0    nvidia
libpng                    1.6.39               h19919ed_0    conda-forge
libsqlite                 3.40.0               hcfcfb64_1    conda-forge
libtiff                   4.5.0                hf8721a0_2    conda-forge
libuv                     1.44.2               h8ffe710_0    conda-forge
libwebp-base              1.3.0                hcfcfb64_0    conda-forge
libxcb                    1.13              hcd874cb_1004    conda-forge
libxml2                   2.10.4               hc3477c8_0    conda-forge
libzlib                   1.2.13               hcfcfb64_4    conda-forge
llvmlite                  0.40.0                   pypi_0    pypi
m2w64-gcc-libgfortran     5.3.0                         6    conda-forge
m2w64-gcc-libs            5.3.0                         7    conda-forge
m2w64-gcc-libs-core       5.3.0                         7    conda-forge
m2w64-gmp                 6.1.0                         2    conda-forge
m2w64-libwinpthread-git   5.0.0.4634.697f757               2    conda-forge
markupsafe                2.1.2           py310h8d17308_0    conda-forge
mkl                       2022.1.0           h6a75c08_874    conda-forge
mkl-devel                 2022.1.0           h57928b3_875    conda-forge
mkl-include               2022.1.0           h6a75c08_874    conda-forge
mpmath                    1.3.0              pyhd8ed1ab_0    conda-forge
msys2-conda-epoch         20160418                      1    conda-forge
natsort                   8.3.1                    pypi_0    pypi
networkx                  3.1                pyhd8ed1ab_0    conda-forge
numba                     0.57.0                   pypi_0    pypi
numpy                     1.24.3          py310hd02465a_0    conda-forge
opencv-python-headless    4.7.0.72                 pypi_0    pypi
openjpeg                  2.5.0                ha2aaf27_2    conda-forge
openssl                   3.1.0                hcfcfb64_3    conda-forge
packaging                 23.1                     pypi_0    pypi
pillow                    9.4.0           py310hdbb7713_1    conda-forge
pip                       23.1.2             pyhd8ed1ab_0    conda-forge
pthread-stubs             0.4               hcd874cb_1001    conda-forge
pthreads-win32            2.9.1                hfa6e2cd_3    conda-forge
pycparser                 2.21               pyhd8ed1ab_0    conda-forge
pygments                  2.15.1                   pypi_0    pypi
pyopenssl                 23.1.1             pyhd8ed1ab_0    conda-forge
pyqt5                     5.15.9                   pypi_0    pypi
pyqt5-qt5                 5.15.2                   pypi_0    pypi
pyqt5-sip                 12.12.1                  pypi_0    pypi
pyqtgraph                 0.13.3                   pypi_0    pypi
pysocks                   1.7.1              pyh0701188_6    conda-forge
python                    3.10.10         h4de0772_0_cpython    conda-forge
python_abi                3.10                    3_cp310    conda-forge
pytorch                   2.0.0           py3.10_cuda11.7_cudnn8_0    pytorch
pytorch-cuda              11.7                 h16d0643_3    pytorch
pytorch-mutex             1.0                        cuda    pytorch
qtpy                      2.3.1                    pypi_0    pypi
requests                  2.29.0             pyhd8ed1ab_0    conda-forge
scipy                     1.10.1                   pypi_0    pypi
setuptools                67.7.2             pyhd8ed1ab_0    conda-forge
superqt                   0.4.1                    pypi_0    pypi
sympy                     1.11.1             pyh04b8f61_3    conda-forge
tbb                       2021.9.0             h91493d7_0    conda-forge
tifffile                  2023.4.12                pypi_0    pypi
tk                        8.6.12               h8ffe710_0    conda-forge
torchaudio                2.0.0                    pypi_0    pypi
torchvision               0.15.0                   pypi_0    pypi
tqdm                      4.65.0                   pypi_0    pypi
typing_extensions         4.5.0              pyha770c72_0    conda-forge
tzdata                    2023c                h71feb2d_0    conda-forge
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
urllib3                   1.26.15            pyhd8ed1ab_0    conda-forge
vc                        14.3                hb25d44b_16    conda-forge
vc14_runtime              14.34.31931         h5081d32_16    conda-forge
vs2015_runtime            14.34.31931         hed1258a_16    conda-forge
wheel                     0.40.0             pyhd8ed1ab_0    conda-forge
win_inet_pton             1.1.0              pyhd8ed1ab_6    conda-forge
xorg-libxau               1.0.9                hcd874cb_0    conda-forge
xorg-libxdmcp             1.1.3                hcd874cb_0    conda-forge
xz                        5.2.6                h8d14728_0    conda-forge
zstd                      1.5.2                h12be248_6    conda-forge
```

**Comment by mrariden** [comment] 2023-05-06 19:13
Duplicate of #701, we'll get it fixed!

**Closed by mrariden** 2023-05-06 19:13 UTC
Labels: bug
