### ISSUE TITLE
3D Tiff in notebook "Value Error: axes don't match array"

### ISSUE THREAD

**Issue by gurugautham** [MouseLand/cellpose#45] opened 2020-04-15 22:21 UTC
Hi,

I'm trying to run a 3D tiff file through cellpose on the notebook. I can convert it to a numpy array and it has the shape (66, 1, 512, 512). I have **do_3D=True**. When I run cellpose, the error I get is:

```
>>>> using CPU
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-7-d13f5a9fc512> in <module>
     23 # you can set the average cell `diameter` in pixels yourself (recommended)
     24 # diameter can be a list or a single number for all images
---> 25 masks, flows, styles, diams = model.eval(imgs, diameter=30, channels=channels, do_3D=True)

~/anaconda3/envs/cellpose/lib/python3.7/site-packages/cellpose/models.py in eval(self, x, channels, diameter, invert, do_3D, net_avg, tile, threshold, rescale, progress)
    155         masks, flows, styles = self.cp.eval(x, invert=invert, rescale=rescale, channels=channels, tile=tile,
    156                                             do_3D=do_3D, net_avg=net_avg, progress=progress,
--> 157                                             threshold=0.4)
    158         return masks, flows, styles, diams
    159 

~/anaconda3/envs/cellpose/lib/python3.7/site-packages/cellpose/models.py in eval(self, x, channels, invert, rescale, do_3D, net_avg, tile, threshold, compute_masks, progress)
    318                 img = x[i].copy()
    319                 if img.shape[0]<3:
--> 320                     img = np.transpose(img, (1,2,0))
    321                 Ly,Lx = img.shape[:2]
    322                 if img.shape[-1]==1:

~/anaconda3/envs/cellpose/lib/python3.7/site-packages/numpy/core/fromnumeric.py in transpose(a, axes)
    573 
    574     """
--> 575     return _wrapfunc(a, 'transpose', axes)
    576 
    577 

~/anaconda3/envs/cellpose/lib/python3.7/site-packages/numpy/core/fromnumeric.py in _wrapfunc(obj, method, *args, **kwds)
     50 def _wrapfunc(obj, method, *args, **kwds):
     51     try:
---> 52         return getattr(obj, method)(*args, **kwds)
     53 
     54     # An AttributeError occurs if the object does not have

ValueError: axes don't match array
```

Any help would be appreciated!

**Comment by BioinfoTongLI** [comment] 2020-04-17 08:17
Hi @gurugautham ,
I also did some 3D seg recently. It worked fine on my sample. 
Could you please print what is your `imgs`?

I am asking simply because I was actually a bit blocked by the input format of 3D stack.
You should give only `one image of (zs, cs, ys, xs)` instead of a list of them, such as the case for 2D images.

Hope that helps
Tong

**Comment by carsen-stringer** [comment] 2020-04-17 14:35
yeah, thanks Tong you are correct, this is the error you would get if you input a list of 4D arrays, sorry for the confusion. Please input just a 4D array, not a list.

**Comment by gurugautham** [comment] 2020-04-18 09:17
@BioinfoTongLI @carsen-stringer thanks for letting me know. I was originally passing the 4D array inside the imgs list to the software. It works when the 4D array is passed alone. This should probably be updated in the "Inputs" part of the documentation :)

**Comment by glossdrop** [comment] 2020-04-18 14:06
Hi @carsen-stringer, I would like to add up to this issue because I am stuck in a situation similar to that of @gurugautham.

When I analyse one single 3D image (gray) from the GUI, everything works perfectly. 
However, when I try to batch the analysis from the terminal for a folder containing 3 (gray) images of the same kind as above (ex, running: `python -m cellpose --dir C:/Users/gloss/Desktop/TEST --pretrained_model nuclei --diameter 0. --save_png --use_gpu`)

I get: 
```
>>>> using GPU
>>>> estimating diameter for each image
running cellpose on 3 images using chan_to_seg GRAY and chan (opt) NONE
processing 3 images
...
>>>> saving results
Traceback (most recent call last):
  File "C:\Users\gloss\anaconda3\envs\cellpose\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\gloss\anaconda3\envs\cellpose\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\INMED\Code_GITHUB\cellpose\cellpose\__main__.py", line 162, in <module>
    io.save_to_png(images, masks, flows, image_names)
  File "D:\INMED\Code_GITHUB\cellpose\cellpose\io.py", line 110, in save_to_png
    plot.show_segmentation(fig, img, maski, flowi)
  File "D:\INMED\Code_GITHUB\cellpose\cellpose\plot.py", line 51, in show_segmentation
    ax.imshow(img0)
  File "C:\Users\gloss\anaconda3\envs\cellpose\lib\site-packages\matplotlib\__init__.py", line 1565, in inner
    return func(ax, *map(sanitize_sequence, args), **kwargs)
  File "C:\Users\gloss\anaconda3\envs\cellpose\lib\site-packages\matplotlib\cbook\deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\gloss\anaconda3\envs\cellpose\lib\site-packages\matplotlib\cbook\deprecation.py", line 358, in wrapper
    return func(*args, **kwargs)
  File "C:\Users\gloss\anaconda3\envs\cellpose\lib\site-packages\matplotlib\axes\_axes.py", line 5615, in imshow
    im.set_data(X)
  File "C:\Users\gloss\anaconda3\envs\cellpose\lib\site-packages\matplotlib\image.py", line 699, in set_data
    .format(self._A.shape))
TypeError: Invalid shape (7, 512, 512) for image data
```

Now I am confused. I understand it is an issue with the tiff file dimensions. My problem is that since they are in one channel only, the images are three dimensional (ZXY) and this doesn't seem to work outside GUI (terminal / notebook).

Is this normal or is there a way around it?
many thanks in advance,
Davide

**Comment by gurugautham** [comment] 2020-04-18 17:42
Hi Davide,

For the notebook, the dimension of each image should be z * channels * x * y. Even if it is grayscale, you’d need to reshape the tiff into z * 1 * x * y. Perhaps you can use a simple python script to convert all the tiff files in your directory to this 4 D shape tiff before running your cellpose command.

**Comment by glossdrop** [comment] 2020-04-18 18:36
Hi @gurugautham, thank you for your feedback.

This is indeed what I tried to do as well on my script. But I get the error message again:
```
processing 7 images
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Users\cavalieri\Anaconda3\envs\cellpose\lib\site-packages\cellpose\models.py", line 164, in eval
    threshold=0.4)
  File "C:\Users\cavalieri\Anaconda3\envs\cellpose\lib\site-packages\cellpose\models.py", line 306, in eval
    x = np.transpose(x, (1,0,2,3))
  File "C:\Users\cavalieri\Anaconda3\envs\cellpose\lib\site-packages\numpy\core\fromnumeric.py", line 598, in transpose
    return _wrapfunc(a, 'transpose', axes)
  File "C:\Users\cavalieri\Anaconda3\envs\cellpose\lib\site-packages\numpy\core\fromnumeric.py", line 51, in _wrapfunc
    return getattr(obj, method)(*args, **kwds)
ValueError: axes don't match array
```

From what I could understand the problem is in `models.py` at lines 305-306:
```
if nimg>1 and do_3D:
    x = np.array(x)
    x = np.transpose(x, (1,0,2,3))
```

Since the initial list containing the image arrays is converted into the 5D array 'x' (#image x Z x channel x X x Y), this does not fit the code anymore. 

I guess that one could run the model.eval() function in a loop but I was wondering if there was anything more efficient.. Or maybe I miss something!

Any advice would be appreciated!
Best,
Davide

**Comment by carsen-stringer** [comment] 2020-05-01 14:33
Sorry for these issues, I've tried to make everything more consistent between 3D and 2D, you can give a list (or not a list) and depending on the do_3D flag it should compute things appropriately.

I've updated the github for now, will update the pip very soon, let me know if you have issues with that.

**Comment by carsen-stringer** [comment] 2020-05-01 14:58
updated pip

```
pip install cellpose --upgrade
```

also 3D should work now without adding the channels as long as you have the do_3D=True parameter, or on command line --do_3D flag

**Comment by carsen-stringer** [comment] 2020-05-09 23:25
since there are emojis on the above post I am going to close this issue :) please comment if you're still having problems

**Closed by carsen-stringer** 2020-05-09 23:25 UTC
