### ISSUE TITLE
Tensor for argument #2 'weight' is on CPU, but expected it to be on GPU

### ISSUE THREAD

**Issue by mcahn** [MouseLand/cellpose#211] opened 2021-02-25 19:15 UTC
This problem was reported as issue #176, and is reported to be fixed, but apparently there is still a way to run Cellpose that produces this error.  I'm using the version from github retrieved on 2/23/2021.

During training it produces this error:

`RuntimeError: Tensor for argument #2 'weight' is on CPU, but expected it to be on GPU (while checking arguments for cudnn_batch_norm)`

The command was:

`python -m cellpose --train --dir /tigress/mcahn/cellpose/training-set --test_dir /tigress/mcahn/cellpose/training-set --img_filter "img" --use_gpu --mask_filter "masks" --learning_rate 0.15 --n_epochs 150 --diameter 0 --pretrained_model cyto`

I doubt this is the appropriate fix, but I was able to avoid this error by changing the default value for the `gpu` argument to `True` in the `__init__()` method of `CellposeModel `in models.py:

```
def __init__(self, gpu=True, pretrained_model=False, torch=True,
                    diam_mean=30., net_avg=True, device=None,
                    residual_on=True, style_on=True, concatenation=False):
```

The full traceback is as follows:

```
Traceback (most recent call last):
  File "/tigress/MOLBIO/local/pythonenv/cellpose/lib/python3.7/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/tigress/MOLBIO/local/pythonenv/cellpose/lib/python3.7/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/tigress/MOLBIO/local/pythonenv/cellpose/lib/python3.7/site-packages/cellpose/__main__.py", line 263, in <module>
    main()
  File "/tigress/MOLBIO/local/pythonenv/cellpose/lib/python3.7/site-packages/cellpose/__main__.py", line 242, in main
    batch_size=args.batch_size)
  File "/tigress/MOLBIO/local/pythonenv/cellpose/lib/python3.7/site-packages/cellpose/models.py", line 645, in train
    learning_rate, n_epochs, momentum, weight_decay, batch_size, rescale)
  File "/tigress/MOLBIO/local/pythonenv/cellpose/lib/python3.7/site-packages/cellpose/core.py", line 947, in _train_net
    train_loss = self._train_step(imgi, lbl)
  File "/tigress/MOLBIO/local/pythonenv/cellpose/lib/python3.7/site-packages/cellpose/core.py", line 809, in _train_step
    y, style = self.net(X)
  File "/tigress/MOLBIO/local/pythonenv/cellpose/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/tigress/MOLBIO/local/pythonenv/cellpose/lib/python3.7/site-packages/cellpose/resnet_torch.py", line 191, in forward
    T0    = self.downsample(data)
  File "/tigress/MOLBIO/local/pythonenv/cellpose/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/tigress/MOLBIO/local/pythonenv/cellpose/lib/python3.7/site-packages/cellpose/resnet_torch.py", line 83, in forward
    xd.append(self.down[n](y))
  File "/tigress/MOLBIO/local/pythonenv/cellpose/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/tigress/MOLBIO/local/pythonenv/cellpose/lib/python3.7/site-packages/cellpose/resnet_torch.py", line 46, in forward
    x = self.proj(x) + self.conv[1](self.conv[0](x))
  File "/tigress/MOLBIO/local/pythonenv/cellpose/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/tigress/MOLBIO/local/pythonenv/cellpose/lib/python3.7/site-packages/torch/nn/modules/container.py", line 117, in forward
    input = module(input)
  File "/tigress/MOLBIO/local/pythonenv/cellpose/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/tigress/MOLBIO/local/pythonenv/cellpose/lib/python3.7/site-packages/torch/nn/modules/batchnorm.py", line 136, in forward
    self.weight, self.bias, bn_training, exponential_average_factor, self.eps)
  File "/tigress/MOLBIO/local/pythonenv/cellpose/lib/python3.7/site-packages/torch/nn/functional.py", line 2058, in batch_norm
    training, momentum, eps, torch.backends.cudnn.enabled
RuntimeError: Tensor for argument #2 'weight' is on CPU, but expected it to be on GPU (while checking arguments for cudnn_batch_norm)
```

Regards,
Matthew Cahn

**Comment by kevinjohncutler** [comment] 2021-03-02 10:14
@carsen-stringer I can reproduce this issue; only happens with a --pretrained_model.

**Comment by saskra** [comment] 2021-04-05 12:44
Same problem here.

**Comment by saskra** [comment] 2021-04-06 09:55
PS: This also happens for me without --pretrained_model.

**Comment by carsen-stringer** [comment] 2021-04-28 00:08
sorry about that, this is fixed now, it is because there are two options, `device` and `gpu`. If `device` is specified it is used instead of `gpu`, but the `gpu` setting did not change for a cuda device. now it changes correctly.

I'm going to close this issue but please let me know if it's still not working.

**Closed by carsen-stringer** 2021-04-28 00:08 UTC

**Comment by saskra** [comment] 2021-05-03 09:44
Thanks, that helped!
