### ISSUE TITLE
[BUG] Unable to train a new model 

### ISSUE THREAD

**Issue by TheSoulMaker** [MouseLand/cellpose#721] opened 2023-05-31 14:31 UTC
Hello ! 

I followed the instructions to train my own mode from a pretrained model.
After saving a first mask corrected manually (Ctrl + S) (a "_seg.npy" file indeed appears in the folder of the image) I press Ctrl+T to create a new custom model. I then press "OK". A new folder named "models" is indeed created in the folder of the image but it's empty and in the console I can see the following message: "
Traceback (most recent call last):
  File "C:\Users\Vladimir\.conda\envs\cellpose\lib\site-packages\cellpose\gui\gui.py", line 1630, in new_model
    self.train_model()
  File "C:\Users\Vladimir\.conda\envs\cellpose\lib\site-packages\cellpose\gui\gui.py", line 1654, in train_model
    self.new_model_path = self.model.train(self.train_data, self.train_labels,
  File "C:\Users\Vladimir\.conda\envs\cellpose\lib\site-packages\cellpose\models.py", line 785, in train
    model_path = self._train_net(train_data, train_flows,
  File "C:\Users\Vladimir\.conda\envs\cellpose\lib\site-packages\cellpose\core.py", line 944, in _train_net
    self.net.save_model(file_name)
  File "C:\Users\Vladimir\.conda\envs\cellpose\lib\site-packages\cellpose\resnet_torch.py", line 218, in save_model
    torch.save(self.state_dict(), filename)
  File "C:\Users\Vladimir\.conda\envs\cellpose\lib\site-packages\torch\serialization.py", line 440, in save
    with _open_zipfile_writer(f) as opened_zipfile:
  File "C:\Users\Vladimir\.conda\envs\cellpose\lib\site-packages\torch\serialization.py", line 315, in _open_zipfile_writer
    return container(name_or_buffer)
  File "C:\Users\Vladimir\.conda\envs\cellpose\lib\site-packages\torch\serialization.py", line 288, in __init__
    super().__init__(torch._C.PyTorchFileWriter(str(name)))
RuntimeError: Parent directory C:/Users/Vladimir/Desktop/Thèse/Projet quadruplet/LifeAct high/TFM intercalation/rotated/intercalation/tissu1\models does not exist."

![image](https://github.com/MouseLand/cellpose/assets/106664267/3ca0a55a-98bc-4b77-884b-7e68e467e304)

I see another person had the same problem but never answered you about it. 
You asked then for the output of conda list so I give it to you now: 
![image](https://github.com/MouseLand/cellpose/assets/106664267/bb65ddf9-46b6-4838-81bd-aa8a038f5d92)

Hoping it helps !
Thank you !

**Comment by mrariden** [comment] 2023-06-03 00:01
This appears to be a duplicate of #671 so I'm going to close this one. Please follow up with more details there. Does `pip install cellpose --upgrade` remedy it?

**Closed by mrariden** 2023-06-03 00:01 UTC
Labels: bug
