### ISSUE TITLE
Running Cellpose with local GPU

### ISSUE THREAD

**Issue by Eddymorphling** [MouseLand/cellpose#360] opened 2021-11-03 21:20 UTC
Hello,
I just started using Cellpose and have been using the executable windows Cellpose .exe file to run my segmentation tasks. I notice that every time I run this, it uses the local CPU instead of the GPU. How can I make Cellpose use the local GPU instead? I currently have an RTX6000 installed and have CUDA11.0 setup on the local PC. 
Any advice would be helpful!

**Comment by Eddymorphling** [comment] 2021-11-03 21:23
Just to add, I tried to setup through Anaconda by following all the instructions given on the Github page, but when I run Cellpose I get the following error:

```
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\cellpose\lib\urllib\request.py", line 1350, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\ProgramData\Anaconda3\envs\cellpose\lib\http\client.py", line 1281, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\ProgramData\Anaconda3\envs\cellpose\lib\http\client.py", line 1327, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\ProgramData\Anaconda3\envs\cellpose\lib\http\client.py", line 1276, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\ProgramData\Anaconda3\envs\cellpose\lib\http\client.py", line 1036, in _send_output
    self.send(msg)
  File "C:\ProgramData\Anaconda3\envs\cellpose\lib\http\client.py", line 976, in send
    self.connect()
  File "C:\ProgramData\Anaconda3\envs\cellpose\lib\http\client.py", line 1451, in connect
    server_hostname=server_hostname)
  File "C:\ProgramData\Anaconda3\envs\cellpose\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "C:\ProgramData\Anaconda3\envs\cellpose\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "C:\ProgramData\Anaconda3\envs\cellpose\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\cellpose\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\ProgramData\Anaconda3\envs\cellpose\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\ProgramData\Anaconda3\envs\cellpose\lib\site-packages\cellpose\__main__.py", line 8, in <module>
    from cellpose import utils, models, io
  File "C:\ProgramData\Anaconda3\envs\cellpose\lib\site-packages\cellpose\models.py", line 58, in <module>
    download_model_weights()
  File "C:\ProgramData\Anaconda3\envs\cellpose\lib\site-packages\cellpose\models.py", line 56, in download_model_weights
    utils.download_url_to_file(url, cached_file, progress=True)
  File "C:\ProgramData\Anaconda3\envs\cellpose\lib\site-packages\cellpose\utils.py", line 55, in download_url_to_file
    u = urlopen(url)
  File "C:\ProgramData\Anaconda3\envs\cellpose\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\ProgramData\Anaconda3\envs\cellpose\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\ProgramData\Anaconda3\envs\cellpose\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\ProgramData\Anaconda3\envs\cellpose\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\ProgramData\Anaconda3\envs\cellpose\lib\urllib\request.py", line 1393, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\ProgramData\Anaconda3\envs\cellpose\lib\urllib\request.py", line 1352, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1091)>
```

**Comment by carsen-stringer** [comment] 2021-11-07 17:30
I'm going to close this because it's a duplicate of #346 , please see the comments there

**Closed by carsen-stringer** 2021-11-07 17:30 UTC
