### ISSUE TITLE
command line mode doesn't work with TIF images in channels_last format

### ISSUE THREAD

**Issue by ngreenwald** [MouseLand/cellpose#148] opened 2020-11-11 22:15 UTC
Running cellpose on a directory of TIF images where the channels dimension is last [rows, cols, chans] doesn't work as expected. No error message is raised, but it treats the image as if is channels_first. For example, when running on a folder of images with shape [256, 256, 2], all of the outputs are shape [256, 2] rather than [256, 256]. It appears that it assumes TIF images are channels_first proceeds accordingly.

**Comment by carsen-stringer** [comment] 2020-11-24 23:00
Can you post the command line input you used? I'm having trouble reproducing this error. I used a tiff that when read in with `tifffile` (which is what cellpose uses) is [384,512,3] and ran
```
python -m cellpose --dir dir_path
```

**Comment by ngreenwald** [comment] 2020-11-25 18:57
Got it, that could be the issue. I created a 2-channel TIF by combining a nuclear and a membrane channel. It wasn't an RGB image, perhaps that's what caused the issue. 

```
python -m cellpose
    --dir path_to_files
    --pretrained_model cyto
    --chan 0 --chan2 1
    --diameter 0.
    --save_tif --use_gpu
```

**Comment by carsen-stringer** [comment] 2020-11-26 14:54
I still can't reproduce this error with a two channel tiff -- btw if you have a 2 channel tiff where cyto is first and nuclei is second, it should be `--chan 1 --chan2 2` (`0` is for gray). I am running the github version of cellpose, maybe that's the difference? travis is making a new pip right now then you can `pip install cellpose --upgrade`.

**Comment by ngreenwald** [comment] 2020-11-26 16:40
Oh you're totally right, thanks!
Yes, we were using the pip version, that could have been the issue. It was easy to resolve, just swapped to channels_first TIFs. 

Thanks!

**Comment by carsen-stringer** [comment] 2020-11-27 00:59
cool, the pip is made, hopefully it works now but it could be that tifffile is still being weird. going to close the issue now.

**Closed by carsen-stringer** 2020-11-27 00:59 UTC
