### ISSUE TITLE
SSL certificate issue trying tro run Cellpose from Anaconda prompt

### ISSUE THREAD

**Issue by MattVXWhelan** [MouseLand/cellpose#346] opened 2021-10-12 12:22 UTC
Hi all, I have followed the instructions for Cellpose installation and appear to have the right dependencies and Python 3.8. Perhaps you can help.

Here is the error:

(base) C:\Users\matth>python -m cellpose
2021-10-12 13:15:19,742 [INFO] WRITING LOG OUTPUT TO C:\Users\matth\.cellpose\run.log
2021-10-12 13:15:19,764 [INFO] Downloading: "https://www.cellpose.org/models/cyto_0" to C:\Users\matth\.cellpose\models\cyto_0

Traceback (most recent call last):
  File "C:\Users\matth\Anaconda3\lib\urllib\request.py", line 1317, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "C:\Users\matth\Anaconda3\lib\http\client.py", line 1244, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\matth\Anaconda3\lib\http\client.py", line 1290, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\matth\Anaconda3\lib\http\client.py", line 1239, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\matth\Anaconda3\lib\http\client.py", line 1026, in _send_output
    self.send(msg)
  File "C:\Users\matth\Anaconda3\lib\http\client.py", line 966, in send
    self.connect()
  File "C:\Users\matth\Anaconda3\lib\http\client.py", line 1414, in connect
    server_hostname=server_hostname)
  File "C:\Users\matth\Anaconda3\lib\ssl.py", line 423, in wrap_socket
    session=session
  File "C:\Users\matth\Anaconda3\lib\ssl.py", line 870, in _create
    self.do_handshake()
  File "C:\Users\matth\Anaconda3\lib\ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\matth\Anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\matth\Anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\matth\Anaconda3\lib\site-packages\cellpose\__main__.py", line 8, in <module>
    from cellpose import utils, models, io
  File "C:\Users\matth\Anaconda3\lib\site-packages\cellpose\models.py", line 58, in <module>
    download_model_weights()
  File "C:\Users\matth\Anaconda3\lib\site-packages\cellpose\models.py", line 56, in download_model_weights
    utils.download_url_to_file(url, cached_file, progress=True)
  File "C:\Users\matth\Anaconda3\lib\site-packages\cellpose\utils.py", line 55, in download_url_to_file
    u = urlopen(url)
  File "C:\Users\matth\Anaconda3\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\matth\Anaconda3\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\matth\Anaconda3\lib\urllib\request.py", line 543, in _open
    '_open', req)
  File "C:\Users\matth\Anaconda3\lib\urllib\request.py", line 503, in _call_chain
    result = func(*args)
  File "C:\Users\matth\Anaconda3\lib\urllib\request.py", line 1360, in https_open
    context=self._context, check_hostname=self._check_hostname)
  File "C:\Users\matth\Anaconda3\lib\urllib\request.py", line 1319, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1076)>

Thanks!

Matt

**Comment by g1-yi** [comment] 2021-10-20 16:08
I'm also having the same issue (see below). have you figured out a solution to this issue yet? 

(cellpose) C:\Users\User>python -m cellpose
2021-10-20 11:01:54,199 [INFO] WRITING LOG OUTPUT TO C:\Users\User\.cellpose\run.log
2021-10-20 11:01:54,215 [INFO] Downloading: "https://www.cellpose.org/models/cyto_0" to C:\Users\User\.cellpose\models\cyto_0

Traceback (most recent call last):
  File "C:\Users\User\anaconda3\envs\cellpose\lib\urllib\request.py", line 1354, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\User\anaconda3\envs\cellpose\lib\http\client.py", line 1256, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\User\anaconda3\envs\cellpose\lib\http\client.py", line 1302, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\User\anaconda3\envs\cellpose\lib\http\client.py", line 1251, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\User\anaconda3\envs\cellpose\lib\http\client.py", line 1011, in _send_output
    self.send(msg)
  File "C:\Users\User\anaconda3\envs\cellpose\lib\http\client.py", line 951, in send
    self.connect()
  File "C:\Users\User\anaconda3\envs\cellpose\lib\http\client.py", line 1425, in connect
    self.sock = self._context.wrap_socket(self.sock,
  File "C:\Users\User\anaconda3\envs\cellpose\lib\ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "C:\Users\User\anaconda3\envs\cellpose\lib\ssl.py", line 1040, in _create
    self.do_handshake()
  File "C:\Users\User\anaconda3\envs\cellpose\lib\ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\User\anaconda3\envs\cellpose\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\User\anaconda3\envs\cellpose\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\User\anaconda3\envs\cellpose\lib\site-packages\cellpose\__main__.py", line 8, in <module>
    from cellpose import utils, models, io
  File "C:\Users\User\anaconda3\envs\cellpose\lib\site-packages\cellpose\models.py", line 58, in <module>
    download_model_weights()
  File "C:\Users\User\anaconda3\envs\cellpose\lib\site-packages\cellpose\models.py", line 56, in download_model_weights
    utils.download_url_to_file(url, cached_file, progress=True)
  File "C:\Users\User\anaconda3\envs\cellpose\lib\site-packages\cellpose\utils.py", line 55, in download_url_to_file
    u = urlopen(url)
  File "C:\Users\User\anaconda3\envs\cellpose\lib\urllib\request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "C:\Users\User\anaconda3\envs\cellpose\lib\urllib\request.py", line 525, in open
    response = self._open(req, data)
  File "C:\Users\User\anaconda3\envs\cellpose\lib\urllib\request.py", line 542, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
  File "C:\Users\User\anaconda3\envs\cellpose\lib\urllib\request.py", line 502, in _call_chain
    result = func(*args)
  File "C:\Users\User\anaconda3\envs\cellpose\lib\urllib\request.py", line 1397, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
  File "C:\Users\User\anaconda3\envs\cellpose\lib\urllib\request.py", line 1357, in do_open
    raise URLError(err)
urllib.error.URLError: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: certificate has expired (_ssl.c:1131)>

**Comment by JulietteDC** [comment] 2021-11-04 09:25
Hi both! I have had the same problem, and I haven't found a way to actually fix the error, but to work around it I installed the models manually. You could probably download them one by one using the URLs (https://www.cellpose.org/models/cyto_0, https://www.cellpose.org/models/cyto_1 etc), but I got all the model files from a colleague who already had it installed and working on his computer. They need to go the .cellpose/models folder. I have put the ones I got from my colleague in a Google folder [here](https://drive.google.com/drive/folders/1ebVyOFiuLe6teQDstyumpUMCvAvl2lhG?usp=sharing).

**Comment by ngotra2710** [comment] 2021-11-07 16:38
Open file request.py
After import lines (after import warnings).
Add these line of code.
`import ssl
ssl._create_default_https_context = ssl._create_unverified_context`

**Comment by carsen-stringer** [comment] 2021-11-07 17:29
I can't reproduce this error, it may be Mac specific? But I've added these lines before the urlopen call, please let me know if it works. You can install the latest version of the code with the command below
```
pip install git+https://github.com/mouseland/cellpose.git
```

**Comment by g1-yi** [comment] 2021-11-08 20:53
> I can't reproduce this error, it may be Mac specific? But I've added these lines before the urlopen call, please let me know if it works. You can install the latest version of the code with the command below
> 
> ```
> pip install git+https://github.com/mouseland/cellpose.git
> ```

I was having this issue on Windows, but this worked! No longer having issues with SSL certification. Thank you so much!

**Comment by carsen-stringer** [comment] 2021-11-08 23:40
Oh oops right I should have noticed you were on Windows, I just default to blaming Mac, glad it's working! going to close this issue

**Closed by carsen-stringer** 2021-11-08 23:40 UTC

**Comment by paolotamag** [comment] 2021-11-12 15:13
Hello there,
this manual command worked for me too (Windows here)
"pip install git+https://github.com/mouseland/cellpose.git"


Despite this, we have a conda env trying to install your package here via KNIME Component (https://kni.me/w/iLCTRXCPDg2EipZJ) 
Unfortunately anaconda is not able to install automatically via
"pip install git+https://github.com/mouseland/cellpose.git"
it will install instead from pip via
"pip install cellpose"

We are going to fix this but in the meantime:

Can you please update the pip repository or fix whatever is wrong there?
That would would make the package easy to use for KNIME users.
Drag, drop, configure, execute: no need to do anything on pip or anaconda.


![2021-11-12_14h21_28](https://user-images.githubusercontent.com/11270852/141489251-00ea0bd4-ed88-4e2e-8e5f-a01935db479b.png)

Thanks
