### ISSUE TITLE
Cell diameter error in large size images

### ISSUE THREAD

**Issue by chenzhao2016** [MouseLand/cellpose#614] opened 2022-12-01 22:08 UTC
hi there, 

I was trying to run Cellpose via the command line for a DAPI channel-only image. The image is large (79,177x 62,642). 

I got this error and Cellpose crushed...

<img width="655" alt="CellPose_error" src="https://user-images.githubusercontent.com/102878000/205168425-90db9551-8063-4a5d-868c-233522b0ffb6.png">

Is this because the image too big??

**Comment by carsen-stringer** [comment] 2023-01-10 14:56
duplicate of #616

**Closed by carsen-stringer** 2023-01-10 14:56 UTC
